allowBuilds:
  electron: true
  electron-winstaller: true
overrides:
  config-chain>ini: ^1.3.8
  app-builder-lib>ejs: ^3.1.10
  workbox-build>glob: ^11.1.0
  tiny-async-pool>semver: ^5.7.2
  '@electron/get>semver': ^6.3.1
  make-dir>semver: ^6.3.1
  '@electron/get>undici': ^7.30.0
  node-gyp>undici: ^6.29.0
  ajv>fast-uri: ^3.1.8
